print (" 1. True and True = %s" % str(True and True))
print (" 2. False and True = %s" % str(False and True))
print (" 3. 1==1 and 2==1 = %s" % ((1==1) and (2==1)))
print (" 4. 'test' == 'test' = %s" % str('test' == 'test'))
print ()